### ISSUE TITLE
Is there a way to call non RTTI functions by using RED4ext?

### ISSUE THREAD

**Issue by BornThisWayfitch** [WopsS/RED4ext.SDK#65]

**Comment by WopsS** [comment]
If you know the address and the signature of the functions, yes.

For example, in [CNamePool](https://github.com/WopsS/RED4ext.SDK/blob/master/include/RED4ext/CNamePool-inl.hpp#L15-L16) we use [RelocFunc](https://github.com/WopsS/RED4ext.SDK/blob/master/include/RED4ext/Relocation.hpp#L18-L38) to do that.

**Comment by BornThisWayfitch** [comment]
Thanks for the answer.

**Comment by WopsS** [comment]
No problem.
